export type Technology = {
  name: string;
  icon: string;
  size: string;
  color: string;
  hidden?: boolean;
  priority?: number;
  areas: ProgrammingArea[];
};

function define<T extends Record<string, Technology>>(t: T) {
  return t;
}

const areas = useProgrammingAreas();
export const technologies = define({
  VUE: {
    name: 'Vue.js',
    icon: 'uim:vuejs',
    size: '20',
    color: '#42b883',
    priority: 1,
    areas: [areas.FRONTEND],
  },
  REACT: {
    name: 'React.js',
    icon: 'mdi:react',
    size: '24',
    color: '#61DAFB',
    priority: 2,
    areas: [areas.FRONTEND],
  },
  NUXT: {
    name: 'Nuxt.js',
    icon: 'lineicons:nuxt',
    size: '24',
    color: '#00C58E',
    priority: 6,
    areas: [areas.FRONTEND],
  },
  NEXT: {
    name: 'Next.js',
    icon: 'tabler:brand-nextjs',
    size: '20',
    color: '#ffffff',
    areas: [areas.FRONTEND],
  },
  VITE: {
    name: 'Vite',
    icon: 'tabler:brand-vite',
    size: '20',
    color: '#646CFF',
    areas: [areas.FRONTEND],
  },
  TAILWIND: {
    name: 'Tailwind',
    icon: 'teenyicons:tailwind-solid',
    size: '22',
    color: '#38B2AC',
    areas: [areas.FRONTEND],
  },
  STYLED_COMPONENTS: {
    name: 'Styled Components',
    icon: 'devicon-plain:styledcomponents',
    size: '20',
    color: '#DB7093',
    areas: [areas.FRONTEND],
  },
  SASS: {
    name: 'Sass',
    icon: 'famicons:logo-sass',
    size: '20',
    color: '#CC6699',
    areas: [areas.FRONTEND],
  },
  PRIMEVUE: {
    name: 'PrimeVue',
    icon: 'simple-icons:primevue',
    size: '20',
    color: '#00C58E',
    hidden: true,
    areas: [areas.FRONTEND],
  },
  REDUX: {
    name: 'Redux',
    icon: 'tabler:brand-redux',
    size: '20',
    color: '#764ABC',
    areas: [areas.FRONTEND],
  },
  GOLANG: {
    name: 'Golang',
    icon: 'fa7-brands:golang',
    size: '24',
    color: '#00ADD8',
    priority: 5,
    areas: [areas.BACKEND],
  },
  RUST: {
    name: 'Rust',
    icon: 'mdi:language-rust',
    size: '24',
    color: '#f95009',
    priority: 5,
    areas: [areas.BACKEND],
  },
  JAVA: {
    name: 'Java',
    icon: 'mdi:language-java',
    size: '20',
    color: '#F38020',
    areas: [areas.BACKEND],
  },
  NODE: {
    name: 'Node.js',
    icon: 'streamline-ultimate:nodesj-logo-bold',
    size: '20',
    color: '#8CC84B',
    priority: 3,
    areas: [areas.BACKEND],
  },
  NESTJS: {
    name: 'NestJS',
    icon: 'file-icons:nestjs',
    size: '20',
    color: '#E0234E',
    priority: 4,
    areas: [areas.BACKEND],
  },
  EXPRESS: {
    name: 'Express.js',
    icon: 'simple-icons:express',
    size: '20',
    color: '#E0234E',
    areas: [areas.BACKEND],
  },
  FASTIFY: {
    name: 'Fastify',
    icon: 'simple-icons:fastify',
    size: '20',
    color: '#FF4B4B',
    areas: [areas.BACKEND],
  },
  MICROSERVICES: {
    name: 'Microservices',
    icon: 'carbon:microservices-1',
    size: '20',
    color: '#4CAF50',
    areas: [areas.BACKEND, areas.DEVOPS, areas.CLOUD],
  },
  WEBSOCKET: {
    name: 'WebSocket',
    icon: 'simple-icons:socketdotio',
    size: '20',
    color: '#F7DF1E',
    areas: [areas.BACKEND],
  },
  SOCKET_IO: {
    name: 'Socket.IO',
    icon: 'simple-icons:socketdotio',
    size: '20',
    color: '#fff',
    areas: [areas.BACKEND, areas.FRONTEND],
  },
  GRAPHQL: {
    name: 'GraphQL',
    icon: 'mdi:graphql',
    size: '20',
    color: '#E10098',
    areas: [areas.BACKEND, areas.FRONTEND],
  },
  TDD: {
    name: 'TDD',
    icon: 'solar:test-tube-bold',
    size: '20',
    color: '#F7DF1E',
    areas: [areas.BACKEND, areas.FRONTEND],
  },
  TYPESCRIPT: {
    name: 'Typescript',
    icon: 'mdi:language-typescript',
    size: '20',
    color: '#007ACC',
    areas: [areas.BACKEND, areas.FRONTEND],
  },
  JAVASCRIPT: {
    name: 'Javascript',
    icon: 'ri:javascript-fill',
    size: '20',
    color: '#F7DF1E',
    areas: [areas.BACKEND, areas.FRONTEND],
  },
  JWT: {
    name: 'JWT',
    icon: 'logos:jwt-icon',
    size: '20',
    color: '#bd1f68ff',
    areas: [areas.BACKEND, areas.FRONTEND],
  },
  TYPEORM: {
    name: 'TypeORM',
    icon: 'simple-icons:typeorm',
    size: '20',
    color: '#fc2f2fff',
    areas: [areas.BACKEND],
  },
  SEQUELIZE: {
    name: 'Sequelize',
    icon: 'simple-icons:sequelize',
    size: '20',
    color: '#52B0E7',
    areas: [areas.BACKEND],
  },
  PRISMA: {
    name: 'Prisma',
    icon: 'simple-icons:prisma',
    size: '20',
    color: '#0C344B',
    areas: [areas.BACKEND],
  },
  SWAGGER: {
    name: 'Swagger',
    icon: 'simple-icons:swagger',
    size: '20',
    color: '#85EA2D',
    areas: [areas.BACKEND],
  },
  APACHE_KAFKA: {
    name: 'Apache Kafka',
    icon: 'simple-icons:apachekafka',
    size: '20',
    color: '#FFF',
    areas: [areas.BACKEND, areas.CLOUD],
  },
  RABBITMQ: {
    name: 'RabbitMQ',
    icon: 'simple-icons:rabbitmq',
    size: '20',
    color: '#FF6600',
    areas: [areas.BACKEND, areas.CLOUD],
  },

  POSTGRESQL: {
    name: 'PostgreSQL',
    icon: 'akar-icons:postgresql-fill',
    size: '20',
    color: '#336791',
    areas: [areas.DATABASES],
  },
  MYSQL: {
    name: 'MySQL',
    icon: 'tabler:brand-mysql',
    size: '20',
    color: '#4479A1',
    areas: [areas.DATABASES],
  },
  MONGODB: {
    name: 'MongoDB',
    icon: 'lineicons:mongodb',
    size: '20',
    color: '#47A248',
    areas: [areas.DATABASES],
  },
  CASSANDRADB: {
    name: 'CassandraDB',
    icon: 'cib:cassandra',
    size: '20',
    color: '#1287B1',
    areas: [areas.DATABASES],
  },
  REDIS: {
    name: 'Redis',
    icon: 'cib:redis',
    size: '20',
    color: '#DC382D',
    areas: [areas.DATABASES],
  },
  FIREBASE: {
    name: 'Firebase',
    icon: 'mdi:firebase',
    size: '20',
    color: '#FFCA28',
    areas: [areas.DATABASES, areas.CLOUD, areas.DEVOPS],
  },

  DOCKER: {
    name: 'Docker',
    icon: 'mdi:docker',
    size: '20',
    color: '#2496ED',
    areas: [areas.DEVOPS],
  },
  KUBERNETES: {
    name: 'Kubernetes',
    icon: 'carbon:kubernetes',
    size: '20',
    color: '#326CE5',
    areas: [areas.DEVOPS],
  },
  LINUX: {
    name: 'Linux',
    icon: 'mdi:linux',
    size: '20',
    color: '#FCC624',
    areas: [areas.DEVOPS],
  },
  NGINX: {
    name: 'Nginx',
    icon: 'cib:nginx',
    size: '20',
    color: '#009639',
    areas: [areas.DEVOPS],
  },
  GIT: {
    name: 'Git',
    icon: 'mdi:git',
    size: '20',
    color: '#F05032',
    areas: [areas.DEVOPS],
  },
  GITHUB: {
    name: 'GitHub',
    icon: 'mdi:github',
    size: '20',
    color: '#fff',
    areas: [areas.DEVOPS],
  },
  GITLAB: {
    name: 'GitLab',
    icon: 'mdi:gitlab',
    size: '20',
    color: '#FC6D26',
    areas: [areas.DEVOPS],
  },
  GITHUB_ACTIONS: {
    name: 'GitHub Actions',
    icon: 'simple-icons:githubactions',
    size: '20',
    color: '#2088FF',
    areas: [areas.DEVOPS],
  },
  CIRCLE_CI: {
    name: 'CircleCI',
    icon: 'simple-icons:circleci',
    size: '20',
    color: '#343434',
    areas: [areas.DEVOPS],
  },
  JENKINS: {
    name: 'Jenkins',
    icon: 'simple-icons:jenkins',
    size: '20',
    color: '#D24939',
    areas: [areas.DEVOPS],
  },
  DEPLOYHQ: {
    name: 'DeployHQ',
    icon: 'logos:deployhq-icon',
    size: '20',
    color: '#4A90E2',
    areas: [areas.DEVOPS],
  },
  DOCKER_HUB: {
    name: 'Docker Hub',
    icon: 'simple-icons:docker',
    size: '20',
    color: '#2496ED',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  DOCKER_COMPOSE: {
    name: 'Docker Compose',
    icon: 'simple-icons:docker',
    size: '20',
    color: '#2496ED',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  DOCKER_SWARM: {
    name: 'Docker Swarm',
    icon: 'simple-icons:docker',
    size: '20',
    color: '#2496ED',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  HELM: {
    name: 'Helm',
    icon: 'simple-icons:helm',
    size: '20',
    color: '#fff',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  TERRAFORM: {
    name: 'Terraform',
    icon: 'simple-icons:terraform',
    size: '20',
    color: '#7B42BC',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  PROMETHEUS: {
    name: 'Prometheus',
    icon: 'simple-icons:prometheus',
    size: '20',
    color: '#E6522C',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  GRAFANA: {
    name: 'Grafana',
    icon: 'simple-icons:grafana',
    size: '20',
    color: '#F46800',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  SONARQUBE: {
    name: 'SonarQube',
    icon: 'simple-icons:sonarqube',
    size: '20',
    color: '#FCA121',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  TRAEFIK: {
    name: 'Traefik',
    icon: 'simple-icons:traefikproxy',
    size: '20',
    color: '#1E9EE8',
    areas: [areas.DEVOPS, areas.CLOUD],
  },
  HASHICORP_VAULT: {
    name: 'HashiCorp Vault',
    icon: 'simple-icons:hashicorp',
    size: '20',
    color: '#4F545C',
    areas: [areas.DEVOPS, areas.CLOUD],
  },

  AWS: {
    name: 'AWS',
    icon: 'flowbite:aws-solid',
    size: '20',
    color: '#FF9900',
    areas: [areas.CLOUD],
  },
  AZURE: {
    name: 'Azure',
    icon: 'simple-icons:microsoftazure',
    size: '20',
    color: '#0089D6',
    areas: [areas.CLOUD, areas.DEVOPS],
  },
  CLOUDFLARE: {
    name: 'Cloudflare',
    icon: 'simple-icons:cloudflare',
    size: '20',
    color: '#F38020',
    areas: [areas.CLOUD, areas.DEVOPS],
  },
  S3: {
    name: 'S3',
    icon: 'simple-icons:amazons3',
    size: '20',
    color: '#569A31',
    areas: [areas.CLOUD],
  },
  SQS: {
    name: 'SQS',
    icon: 'simple-icons:amazonsqs',
    size: '20',
    color: '#FF9900',
    areas: [areas.CLOUD],
  },
  LAMBDA: {
    name: 'Lambda',
    icon: 'simple-icons:awslambda',
    size: '20',
    color: '#FF9900',
    areas: [areas.CLOUD],
  },
  MINIO: {
    name: 'MinIO',
    icon: 'simple-icons:minio',
    size: '20',
    color: '#F68B20',
    areas: [areas.CLOUD],
  },

  KOTLIN: {
    name: 'Kotlin',
    icon: 'mdi:language-kotlin',
    size: '20',
    color: '#0095D5',
    areas: [areas.BACKEND, areas.MOBILE, areas.DESKTOP],
  },
  ANDROID: {
    name: 'Android',
    icon: 'mdi:android',
    size: '20',
    color: '#3DDC84',
    areas: [areas.MOBILE],
  },
  FLUTTER: {
    name: 'Flutter',
    icon: 'ri:flutter-fill',
    size: '20',
    color: '#02569B',
    areas: [areas.MOBILE, areas.DESKTOP, areas.FRONTEND],
  },
  TAURI: {
    name: 'Tauri',
    icon: 'devicon-plain:tauri',
    size: '20',
    color: '#F7DF1E',
    areas: [areas.FRONTEND, areas.DESKTOP, areas.MOBILE],
  },

  ESLINT: {
    name: 'ESLint',
    icon: 'simple-icons:eslint',
    size: '20',
    color: '#4B32C3',
    areas: [areas.BACKEND, areas.FRONTEND],
  },
  JEST: {
    name: 'Jest',
    icon: 'simple-icons:jest',
    size: '20',
    color: '#C21325',
    areas: [areas.BACKEND, areas.FRONTEND],
  },
  BUBBLETEA: {
    name: 'Bubbletea',
    icon: 'streamline-plump:erlenmeyer-flask-solid',
    size: '20',
    color: '#00ADD8',
    hidden: true,
    areas: [areas.BACKEND],
  },
  LIPGLOSS: {
    name: 'Lipgloss',
    icon: 'lets-icons:flask',
    size: '20',
    color: '#FF6F61',
    hidden: true,
    areas: [areas.BACKEND],
  }
});

export type TechnologyKey = keyof typeof technologies;
export function useTechnologies(): Record<TechnologyKey, Technology> {
  return technologies;
}
